from test2 import *
from matrix import linear_dept_cols,solve_matrix
xs = np.array([0,-1,1,2,2,1,-1,-1,1,2])
ys = np.array([0,0,0,0,2,1,1,-1,-1,-2])
A = node_test2(xs,ys,3)
# xs = np.arange(-7,8)
# ys = np.zeros(15)
# A = node_test2(xs,ys,4)
cols = linear_dept_cols(A)
wh = np.where(cols==0)
plt.plot(xs,ys,'bo')
plt.plot(xs[wh],ys[wh],'ro')
plt.show()
# b = np.zeros(15)
# b[0] = factorial(4)
b = np.zeros(10)
b[0] = factorial(3)
soln = solve_matrix(A,b)
